# This workflow will install Python dependencies and run tests
name: Python Test CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
      - name: Run tests
        run: |
          coverage run -m unittest
      - name: Generate coverage report
        run: |
          coverage xml
      - name: Upload coverage report to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage.xml
          # or a comma-separated list for multiple reports
          # coverage-reports: coverage.xml, coverage2.xml